name: Check release
on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repository
        required: false
      domain:
        description: Git service domain
        default: github.com
        required: false
      scheme:
        description: Git service scheme
        default: https
        required: false
jobs:
  release_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get release
        id: getter
        uses: ./.github/actions/get-release
        with:
          repo: ${{ github.event.inputs.repo }}
          scheme: ${{ github.event.inputs.scheme }}
          domain: ${{ github.event.inputs.domain }}
      - name: Result
        run: |
          echo "id: ${{ steps.getter.outputs.id }}"
          echo "tag: ${{ steps.getter.outputs.tag }}"
          echo "name: ${{ steps.getter.outputs.name }}"

          echo "id: ${{ steps.gh-info.outputs.id }}"
          echo "tag: ${{ steps.gh-info.outputs.tag }}"
          echo "name: ${{ steps.gh-info.outputs.name }}"

          echo "id: ${{ steps.gl-info.outputs.id }}"
          echo "tag: ${{ steps.gl-info.outputs.tag }}"
          echo "name: ${{ steps.gl-info.outputs.name }}"

          echo "getter suka: ${{ steps.getter.outputs.suka }}"
          echo "getter suka2: ${{ steps.getter.outputs.suka2 }}"
          echo "gh-info suka: ${{ steps.gh-info.outputs.suka }}"
          echo "gh-info suka2: ${{ steps.gh-info.outputs.suka2 }}"
          echo "gl-info suka: ${{ steps.gl-info.outputs.suka }}"
          echo "gl-info suka2: ${{ steps.gl-info.outputs.suka2 }}"
