name: Check release
on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repository
        default: gitlab-org/gitlab-runner
        required: false
      domain:
        description: Git service domain
        default: gitlab.com
        required: false
      scheme:
        description: Git service scheme
        default: https
        required: false
jobs:
  release_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get release
        id: getter
        uses: ./.github/actions/get-release
        with:
          repo: ${{ github.event.inputs.repo }}
          scheme: ${{ github.event.inputs.scheme }}
          domain: ${{ github.event.inputs.domain }}
      - name: Result
        run: |
          echo "id: ${{ steps.getter.outputs.id }}"
          echo "tag: ${{ steps.getter.outputs.tag }}"
          echo "name: ${{ steps.getter.outputs.name }}"
